//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_estate_agency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartment()
        {
            this.Buy_apartment = new HashSet<Buy_apartment>();
            this.Rent_apartment = new HashSet<Rent_apartment>();
        }
    
        public int ID { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public string Addres { get; set; }
        public double Cadastral_number { get; set; }
        public int Owner { get; set; }
        public int Apartment_floor { get; set; }
        public int Floors_House { get; set; }
        public int Number_of_rooms { get; set; }
        public int Area { get; set; }
        public string Image { get; set; }
        public double Price { get; set; }
        public int Ad_types { get; set; }
        public string S
        {
            get
            {
                string ss = $"{Area}";
                return ss;
            }
        }
       
        public virtual Ad_type Ad_type { get; set; }
        public virtual Client Client { get; set; }
        public virtual Property_condition Property_condition { get; set; }
        public virtual Property_type Property_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buy_apartment> Buy_apartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent_apartment> Rent_apartment { get; set; }
    }
}
