//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_estate_agency
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Buy_home
    {
        public int ID { get; set; }
        public int Home { get; set; }
        public int Owner { get; set; }
        public int Buyer { get; set; }
        public System.DateTime Date_Dogovor { get; set; }
        public int Type_payment { get; set; }
        public int Staff { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual Home Home1 { get; set; }
        public virtual Payment_type Payment_type { get; set; }
        public virtual Staff Staff1 { get; set; }
        [NotMapped]
        public Client BuyAppartment
        {
            get
            {
                return DataWorker.GetClient(Owner);
            }
        }
        public Client BuyAppartment1
        {
            get
            {
                return DataWorker.GetClient(Buyer);
            }
        }
        public Apartment Adres
        {
            get
            {
                return DataWorker.GetKvatir(Home);
            }
        }
    }
}
