//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_estate_agency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Real_estate_agencyEntities5 : DbContext
    {
        public Real_estate_agencyEntities5()
            : base("name=Real_estate_agencyEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad_type> Ad_type { get; set; }
        public virtual DbSet<Apartment> Apartment { get; set; }
        public virtual DbSet<Buy_apartment> Buy_apartment { get; set; }
        public virtual DbSet<Buy_home> Buy_home { get; set; }
        public virtual DbSet<Buy_premises> Buy_premises { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Home> Home { get; set; }
        public virtual DbSet<Payment_type> Payment_type { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Premises> Premises { get; set; }
        public virtual DbSet<Property_condition> Property_condition { get; set; }
        public virtual DbSet<Property_type> Property_type { get; set; }
        public virtual DbSet<Rent_apartment> Rent_apartment { get; set; }
        public virtual DbSet<Rent_home> Rent_home { get; set; }
        public virtual DbSet<Rent_promises> Rent_promises { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
